In [1]:
import numpy as np

In [2]:
import matplotlib.pyplot as plt

# 1)

In [3]:
matrix_A = np.array([[2,2,3],[-2,7,4], [-3,-3,-4], [-8,2,3]])
print (matrix_A)

[[ 2  2  3]
 [-2  7  4]
 [-3 -3 -4]
 [-8  2  3]]


# i)

In [4]:
new_column = np.array([[1],[2],[3],[4]])
new_matrix= np.hstack((matrix_A,new_column))     #hstack adds anew column
new_matrix                                 #vstack adds a new raw


array([[ 2,  2,  3,  1],
       [-2,  7,  4,  2],
       [-3, -3, -4,  3],
       [-8,  2,  3,  4]])

In [5]:
determinant = np.linalg.det(new_matrix)
print(determinant)

-542.9999999999999


# ii)

In [6]:
matrix_A = np.array([[2,2,3],[-2,7,4], [-3,-3,-4], [-8,2,3]])
reduced_matrix = np.delete(matrix_A,3,axis=0)   #axis=0 is the row to be deleted
print(reduced_matrix)                             #axis=1 is the colum to be deleted

[[ 2  2  3]
 [-2  7  4]
 [-3 -3 -4]]


 # III)

In [7]:
AT= np.transpose(matrix_A)
print(AT)

[[ 2 -2 -3 -8]
 [ 2  7 -3  2]
 [ 3  4 -4  3]]


In [8]:
AAT =np.dot(matrix_A,AT)
print(AAT)

[[ 17  22 -24  -3]
 [ 22  69 -31  42]
 [-24 -31  34   6]
 [ -3  42   6  77]]


In [9]:
determinant = np.linalg.det(AAT) #its inverteble
print(determinant)               #if its equal to zero then its not invertable

3.3772984409097314e-12


# iv)

In [10]:
AT= np.transpose(matrix_A)
print(AT)

[[ 2 -2 -3 -8]
 [ 2  7 -3  2]
 [ 3  4 -4  3]]


In [11]:
ATA = np.dot(AT,matrix_A)
ATA

array([[ 81, -17, -14],
       [-17,  66,  52],
       [-14,  52,  50]])

In [12]:
determinant = np.linalg.det(ATA)
determinant                             #Its invertable because its determinant is not egual to zero

np.float64(45642.00000000001)


# 2 )

# i)

In [13]:
x = ([[25,2],[5,26],[3,7]])

In [14]:
x = np.array([[25,2],[5,26],[3,7]])
x

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

# ii )

In [15]:
x = x.shape
x

(3, 2)

# iii)

In [16]:
A= ([[3,4],[5,6],[7,8]])

In [17]:
x = ([[25,2],[5,26],[3,7]])

In [18]:
xT = np.transpose(x)       #transposing matrix A so that its equal to matrix X for better multiplication
xT

array([[25,  5,  3],
       [ 2, 26,  7]])

In [19]:
multiplied_matrix = xT.dot(A)    #the multiplied matrix  
multiplied_matrix

array([[121, 154],
       [185, 220]])

# iv)

In [20]:
inverse = np.linalg.inv(multiplied_matrix)
inverse

array([[-0.11764706,  0.08235294],
       [ 0.09893048, -0.06470588]])

# 3)

# i)

In [21]:
x = np.array([25,2,5])
x

array([25,  2,  5])

# ii)

In [22]:
shape = x.shape
shape

(3,)

# iv)

In [23]:
transpose_x = x.T
transpose_x

array([25,  2,  5])

In [24]:
transpose_x = np.transpose(x)    # alternatively
transpose_x

array([25,  2,  5])

# v)

In [25]:
norm_2 = np.linalg.norm(x)
norm_2

np.float64(25.573423705088842)